name: dotnet/code-analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Run NuGet restore
      run: dotnet restore ./ConsoleApp1/ConsoleApp1.sln

    - name: Run .NET Code Analysis
      uses: dotnet/code-analysis@v1
      id: code-analysis
      with:
        solution: ConsoleApp1.sln
        build-breaking: true
        all-categories: all
        sarifFile: ./dotnetAnalyzers_result.sarif
        
    - uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ./dotnetAnalyzers_result.sarif 
